version: '3.4'

services:
  authentiq-db:
    image: sayid/alpine-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: authentiq
      MONGO_INITDB_ROOT_PASSWORD: authentiqrocks
    logging:
      driver: 'none'
    restart: unless-stopped
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/authentiq --quiet"
      interval: 45s
      timeout: 10s
      retries: 10
      start_period: 15s
    volumes:
      - db-data:/data/db

  authentiq:
    image: sayid/authentiq:alpine-1
    environment:
      DB: mongodb://authentiq-db:27017/authentiq
    depends_on:
      - authentiq-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/authentiq/v1/heartbeat"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    ports:
      - '2052:2000'

volumes:
  db-data:
